# Generated by Django 3.1.2 on 2020-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycorona',
            name='new_cure',
        ),
        migrations.RemoveField(
            model_name='dailycorona',
            name='new_death',
        ),
        migrations.RemoveField(
            model_name='dailycorona',
            name='new_positive',
        ),
        migrations.RemoveField(
            model_name='dailycorona',
            name='new_test',
        ),
        migrations.RemoveField(
            model_name='sumcorona',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sumcorona',
            name='new_cure',
        ),
        migrations.RemoveField(
            model_name='sumcorona',
            name='new_death',
        ),
        migrations.RemoveField(
            model_name='sumcorona',
            name='new_positive',
        ),
        migrations.RemoveField(
            model_name='sumcorona',
            name='new_test',
        ),
        migrations.AddField(
            model_name='dailycorona',
            name='cured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycorona',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycorona',
            name='domestic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycorona',
            name='oversea',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycorona',
            name='positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycorona',
            name='quarantined',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycorona',
            name='test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sumcorona',
            name='cured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sumcorona',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sumcorona',
            name='domestic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sumcorona',
            name='oversea',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sumcorona',
            name='positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sumcorona',
            name='test',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sumcorona',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
