# Generated by Django 3.1.2 on 2020-11-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20201104_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumcorona',
            name='quarantined',
            field=models.IntegerField(default=0),
        ),
    ]
