# Generated by Django 3.1.2 on 2020-11-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_sumcorona_quarantined'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumcorona',
            name='negative',
            field=models.IntegerField(default=0),
        ),
    ]
