# Generated by Django 3.1.2 on 2020-11-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_sumcorona_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumcorona',
            name='in_test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sumcorona',
            name='pos_neg',
            field=models.IntegerField(default=0),
        ),
    ]
