# Generated by Django 3.1.2 on 2020-11-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20201104_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumcorona',
            name='date',
            field=models.DateField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
