# Generated by Django 3.1.2 on 2020-11-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20201106_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycorona',
            name='test',
        ),
    ]
